const activityTypes = {
    garmin: {
        RUNNING: 'running',
        INDOOR_RUNNING: 'running',
        STREET_RUNNING: 'running',
        TRACK_RUNNING: 'running',
        TRAIL_RUNNING: 'running',
        ULTRA_RUN: 'running',
        INDOOR_CYCLING: 'running',
        CYCLING: 'bike',
        MOUNTAIN_BIKING: 'bike',
        ROAD_BIKING: 'bike',
        TRACK_CYCLING: 'bike',
        ELLIPTICAL: 'elliptical',
        INDOOR_CARDIO: 'functional',
        STRENGTH_TRAINING: 'functional',
        HIIT: 'functional',
        BMX: 'bike',
        CYCLOCROSS: 'bike',
        DOWNHILL_BIKING: 'bike',
        E_BIKE_FITNESS: 'bike',
        E_BIKE_MOUNTAIN: 'bike',
        GRAVEL_CYCLING: 'bike',
        INDOOR_CYCLING: 'bike',
        MOUNTAIN_BIKING: 'bike',
        RECUMBENT_CYCLING: 'bike',
        ROAD_BIKING: 'bike',
        TRACK_CYCLING: 'bike',
        VIRTUAL_RIDE: 'bike',
        HANDCYCLING: 'bike',
        INDOOR_HANDCYCLING: 'bike',
        LAP_SWIMMING: 'cardio',
        OPEN_WATER_SWIMMING: 'cardio',
    },
    coros: {},
    strava: {},
    suunto: {},
    polar: {},
};

export default activityTypes;
