export default {
    error: null,
    payload: {
        workoutId: 0,
        activityId: 1,
        startTime: 1729199813635,
        totalTime: 2854.48,
        totalDistance: 5952.0,
        totalAscent: 0.0,
        totalDescent: 0.0,
        startPosition: {
            x: -60.007173333333334,
            y: -34.89172333333333,
        },
        stopPosition: {
            x: -60.00855,
            y: -34.890633333333334,
        },
        centerPosition: {
            x: -60.007506666666664,
            y: -34.89029166666667,
        },
        maxSpeed: 3.25,
        stepCount: 6466,
        recoveryTime: 32760,
        cumulativeRecoveryTime: 32760,
        rankings: {
            totalTimeOnRouteRanking: {
                originalRanking: 4,
                originalNumberOfWorkouts: 5,
            },
        },
        extensionTypes: [
            'ALTITUDESTREAM',
            'BATTERYLEVELSTREAM',
            'CADENCESTREAM',
            'DISTANCEDELTA',
            'DISTANCELAP',
            'FITNESS',
            'HEARTRATE',
            'HEARTRATESTREAM',
            'INTENSITY',
            'LOCATIONSTREAM',
            'MANUALLAP',
            'PAUSEMARKER',
            'SEALEVELPRESSURESTREAM',
            'SML',
            'SPEEDSTREAM',
            'SUMMARY',
            'TEMPERATURESTREAM',
            'VERTICALSPEEDSTREAM',
            'WEATHER',
        ],
        minAltitude: 492.0,
        maxAltitude: 532.0,
        isEdited: false,
        isManuallyAdded: false,
        tss: {
            calculationMethod: 'PACE',
            trainingStressScore: 7.8523164,
            intensityFactor: 0.419979,
            normalizedPower: null,
            averageGradeAdjustedPace: 2.0987444,
        },
        tssList: [
            {
                calculationMethod: 'PACE',
                trainingStressScore: 7.8523164,
                intensityFactor: 0.419979,
                normalizedPower: null,
                averageGradeAdjustedPace: 2.0987444,
            },
            {
                calculationMethod: 'HR',
                trainingStressScore: 32.38426,
                intensityFactor: null,
                normalizedPower: null,
                averageGradeAdjustedPace: 2.0987444,
            },
            {
                calculationMethod: 'MET',
                trainingStressScore: 44.40302,
                intensityFactor: null,
                normalizedPower: null,
                averageGradeAdjustedPace: null,
            },
        ],
        suuntoTags: ['IMPACT_AEROBIC'],
        avgSpeed: 2.09,
        avgSpeedInKmH: 7.523999999999999,
        avgPace: 7.99,
        pictureCount: 0,
        hrdata: {
            workoutMaxHR: 168,
            workoutAvgHR: 136,
            userMaxHR: 198,
            hrmax: 168,
            avg: 136,
            max: 198,
        },
        timeOffsetInMinutes: -180,
        cadence: {
            max: 166,
            avg: 74,
        },
        commentCount: 0,
        viewCount: 0,
        energyConsumption: 497,
        workoutKey: '6711919055a9220c7471d6c2',
    },
    metadata: {
        ts: '1729213787702',
    },
};
